[package]
name = "vsift-application"
description = "Application use cases and ports for VSift"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
vsift-domain.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true

