[package]
name = "vsift-infrastructure"
description = "Infrastructure adapters for VSift"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
process-wrap.workspace = true
tokio.workspace = true
vsift-application.workspace = true
vsift-domain.workspace = true

[lints]
workspace = true
