[package]
name = "vsift-domain"
description = "Core domain types for VSift"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
