#!/usr/bin/env node
'use strict';

// P14 RQ-10: hostile media, sidecars and file names through the PUBLISHED
// `vsift`, in a disposable container with no network, a read-only root, and
// memory, process and CPU limits, on a hosted Ubuntu 24.04 runner prepared by
// prepare-host.cjs. Every hostile input is generated by code at run time
// (lib/hostile-cases.cjs) from the corpus's own fixtures; nothing is
// downloaded, nothing real is used, nothing is committed. Each operation must
// end in a typed failure (or, where the case allows, a result) inside its
// bounds, with no hang, no network, no file outside the root and nothing in
// its output a terminal would act on.
//
//   node hostile-media.cjs --out <dir> --repo <checkout> [--only <id or group prefix>]
//
// Never run it on a machine whose state matters: it builds hostile files under
// /srv/vsift, a FIFO and a 30 GiB sparse file among them, and runs containers.

const crypto = require('node:crypto');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const host = require('./lib/host.cjs');
const container = require('./lib/container.cjs');
const cases = require('./lib/hostile-cases.cjs');
const judge = require('./lib/hostile-judge.cjs');

const WORKSPACE = `${host.STATE}/ws-hostile`;
const WORKER_WORKSPACE = `${host.STATE}/ws-hostile-worker`;
const SMALL_WORKSPACE = `${host.STATE}/ws-small`;
const HOSTILE = `${host.INPUTS}/hostile`;

function parse(argv) {
  const options = {};
  for (let index = 0; index < argv.length; index += 2) options[argv[index].replace(/^--/, '')] = argv[index + 1];
  for (const required of ['out', 'repo']) if (!options[required]) throw new Error(`--${required} is required`);
  return options;
}

const log = (message) => process.stdout.write(`${new Date().toISOString().slice(11, 19)} ${message}\n`);

let counter = 0;

/** One command in a hostile-input container: no network, 1 GiB, 128 processes, 2 CPUs. */
async function run(command, spec = {}) {
  counter += 1;
  const name = `vsift-hostile-${counter}`;
  const args = container.runArguments({
    image: host.IMAGE,
    name,
    command: ['case-wrapper', ...command],
    network: 'none',
    cpus: 2,
    memory: '1g',
    pids: 128,
    volumes: [`${host.STATE}:${host.STATE}:rw`, `${host.INPUTS}:${host.INPUTS}:ro`, `${host.BUNDLES}:${host.BUNDLES}:rw`],
    extra: spec.tmpfs ? ['--tmpfs', `${SMALL_WORKSPACE}:rw,size=${spec.tmpfs}m,uid=10001,gid=10001,mode=0700`] : [],
  });
  const result = await container.docker(args, { timeoutMs: judge.BOUNDS.wallMs + 30_000, killName: name });
  const state = container.state(name);
  container.remove(name);
  return { ...result, oomKilled: Boolean(state && state.oomKilled), network: state ? state.network : null };
}

/** The `vsift` arguments of each operation. */
function commandFor(op, spec, session, workspace) {
  const root = ['--session-root', workspace];
  const source = spec.transcript ? `${host.INPUTS}/incoming/F10.mp4` : `${HOSTILE}/${spec.file}`;
  switch (op) {
    case 'ingest':
      return ['vsift', ...root, 'ingest', source, ...(spec.transcript ? ['--transcript', `${HOSTILE}/${spec.transcript}`] : []), '--json'];
    case 'ingest_human':
      return ['vsift', ...root, 'ingest', source];
    case 'candidates':
      return ['vsift', ...root, 'candidates', session, '--from', '0', '--to', '60000000', '--json'];
    case 'frame':
      return ['vsift', ...root, 'frame', 'get', session, '--at', '1000000', '--json'];
    case 'audio':
      return ['vsift', ...root, 'audio', session, '--from', '0', '--to', '2000000', '--json'];
    case 'recognise':
      return ['vsift', ...root, 'transcript', 'retranscribe', session, '--from', '0', '--to', '5000000', '--json'];
    case 'job_name':
      return ['vsift', '--host-isolation', 'strict-linux', '--session-root', WORKER_WORKSPACE, 'job', 'run', '--request', `${host.STATE}/queue/hostile-request.json`, '--input-root', host.INPUTS, '--bundle-root', host.BUNDLES, '--json'];
    case 'job_small':
      // A worker workspace made on the small filesystem, then the request: the free-space reserve is enforced there.
      return ['sh', '-c', `vsift --session-root ${SMALL_WORKSPACE}/w session init-workspace --durability ephemeral --admission-slots 4 --retention-hours 1 --json > /dev/null && vsift --host-isolation strict-linux --session-root ${SMALL_WORKSPACE}/w job run --request ${host.STATE}/queue/hostile-request.json --input-root ${host.INPUTS} --bundle-root ${host.BUNDLES} --json`];
    default:
      throw new Error(`unknown operation ${op}`);
  }
}

async function runCase(spec, canaries) {
  const results = [];
  let session = null;
  let accepted = true;
  for (const [index, op] of spec.ops.entries()) {
    if (index > 0 && !accepted && op !== 'ingest_human' && op !== 'job_name' && op !== 'job_small') break;
    if (op === 'job_name' || op === 'job_small') {
      const body = JSON.stringify({ schema_version: '1', operation_id: `op_${crypto.createHash('sha256').update(spec.id).digest('hex').slice(0, 32)}`, durability: 'ephemeral', target: { ingest: { source: `hostile/${spec.file}`, transcript: null } }, steps: [{ close: {} }] });
      host.sudo(['sh', '-c', `cat > ${host.STATE}/queue/hostile-request.json && chown ${container.WORKER_USER} ${host.STATE}/queue/hostile-request.json`], { input: body });
    }
    // EVIDENCE-ONLY REVISION (never merged): the session root is a folder VSift creates inside the small
    // filesystem, not the mount point itself (an existing folder VSift did not create is refused as INTEGRITY_FAILURE
    // after a wait, install.md section 12), so that `ingest` reaches the free-space check of #266.
    const workspace = spec.tmpfs && op !== 'job_small' ? `${SMALL_WORKSPACE}/root` : WORKSPACE;
    const answered = await run(commandFor(op, spec, session, workspace), { tmpfs: spec.tmpfs });
    const verdict = judge.judge({ spec, op, first: index === 0 || op === 'job_name' || op === 'job_small' || op === 'ingest_human', run: answered, canaries });
    if (op === 'ingest') {
      const ok = verdict.json && (verdict.json.status === 'complete' || verdict.json.status === 'partial');
      accepted = Boolean(ok);
      session = ok && verdict.json.data ? verdict.json.data.session_id : null;
      if (ok) accepted = Boolean(session);
    }
    results.push({
      op,
      outcome: verdict.outcome,
      ok: verdict.ok,
      findings: verdict.findings,
      seconds: Math.round(answered.durationMs / 100) / 10,
      memoryPeakMiB: verdict.metrics && verdict.metrics.memoryPeak !== null ? Math.round(verdict.metrics.memoryPeak / 1048576) : null,
      pidsPeak: verdict.metrics ? verdict.metrics.pidsPeak : null,
      exit: answered.code,
    });
  }
  if (spec.expect === 'refused') {
    const finding = judge.refusedSomewhere(results);
    if (finding) results.push({ op: '(case)', outcome: 'not refused', ok: false, findings: [finding], seconds: 0, memoryPeakMiB: null, pidsPeak: null, exit: null });
  }
  return results;
}

/** The findings already filed as issues, by case id: a run that finds only these does not fail (judge.splitKnown). */
const TRACKED = Object.freeze({ fifo: 264, 'symlink-to-canary': 265, 'sparse-no-room': 266 });

function markdown(report) {
  const headline = report.ok
    ? 'every operation held'
    : report.fresh.length === 0 && report.containmentOk
      ? `FINDINGS, all tracked (${report.known.map((entry) => `#${entry.issue}`).filter((issue, index, all) => all.indexOf(issue) === index).join(', ')})`
      : 'NEW FINDINGS';
  const lines = [`## P14 malicious media (RQ-10): ${headline}`, ''];
  lines.push(`${report.cases} inputs, ${report.operations} operations, ${report.findings} finding(s); the slowest operation took ${report.slowestSeconds} s and the largest memory peak was ${report.peakMiB} MiB of the 1,024 MiB limit; no operation had a network.`, '');
  lines.push('| Group | Input | What it is | Operations: outcome (seconds, MiB) |', '| --- | --- | --- | --- |');
  for (const entry of report.results) {
    const ops = entry.results.map((result) => `${result.ok ? '' : '**FAIL** '}${result.op}: ${result.outcome} (${result.seconds} s${result.memoryPeakMiB === null ? '' : `, ${result.memoryPeakMiB} MiB`})`).join('; ');
    lines.push(`| ${entry.group} | \`${entry.id}\` | ${entry.description.replace(/\|/g, '\\|').slice(0, 150)} | ${ops.replace(/\|/g, '\\|')} |`);
  }
  lines.push('');
  if (report.findingsList.length > 0) {
    lines.push('### Findings', '');
    for (const finding of report.findingsList) lines.push(`- \`${finding.id}\` ${finding.op}: ${finding.findings.join('; ')}${TRACKED[finding.id] ? ` (tracked: #${TRACKED[finding.id]})` : ' (NEW)'}`);
    for (const id of report.fixed) lines.push(`- \`${id}\` is tracked and now passes: remove it from TRACKED`);
    lines.push('');
  }
  lines.push('### Containment', '', '| Check | Result | Detail |', '| --- | --- | --- |');
  for (const check of report.containment) lines.push(`| ${check.name} | ${check.ok ? 'pass' : '**FAIL**'} | ${String(check.detail).replace(/\|/g, '\\|')} |`);
  lines.push('');
  return lines.join('\n');
}

async function main() {
  const options = parse(process.argv.slice(2));
  fs.mkdirSync(options.out, { recursive: true });
  const user = os.userInfo();
  const base = fs.readFileSync(path.join(options.repo, 'fixtures', 'corpus', 'generated', 'F01.mp4'));
  const context = { fixture: (name) => fs.readFileSync(path.join(options.repo, 'fixtures', 'corpus', 'generated', name)) };

  // The canary lives outside the input root and the workspaces; nothing may read it into an output or change it.
  const canary = `OUTSIDE-CANARY-${crypto.randomBytes(8).toString('hex')}`;
  host.sudo(['sh', '-c', `printf '%s\\n' '${canary}' > ${cases.CANARY_PATH} && chmod 0644 ${cases.CANARY_PATH}`]);
  const canaryDigest = crypto.createHash('sha256').update(`${canary}\n`).digest('hex');

  host.sudo(['mkdir', '-p', HOSTILE, `${host.STATE}/queue`]);
  host.sudo(['chown', `${user.uid}:${user.gid}`, HOSTILE]);
  const everything = [...cases.cases(context), ...cases.nameCases(context)];
  const chosen = options.only ? everything.filter((entry) => entry.id.startsWith(options.only) || entry.group === options.only) : everything;

  log(`generating ${chosen.length} hostile inputs below ${HOSTILE}`);
  const made = {};
  for (const spec of chosen) {
    try {
      made[spec.id] = await cases.materialise(HOSTILE, spec);
    } catch (error) {
      throw new Error(`could not build ${spec.id}: ${error.message}`);
    }
  }
  host.run('chmod', ['-R', 'a+rX', HOSTILE]);
  host.sudo(['sh', '-c', `touch ${host.STATE}/queue/p14-stamp`]);
  await new Promise((resolve) => setTimeout(resolve, 1500));

  // Workspaces: one for the desktop commands, one worker workspace for the request path.
  for (const [workspace, command] of [
    [WORKSPACE, null],
    [WORKER_WORKSPACE, ['session', 'init-workspace', '--durability', 'ephemeral', '--admission-slots', '4', '--retention-hours', '1']],
  ]) {
    if (command) {
      const initialised = await run(['vsift', '--session-root', workspace, ...command, '--json']);
      if (initialised.code !== 0) throw new Error(`could not initialise the worker workspace: ${initialised.stdout.slice(0, 400)}`);
    }
  }

  const results = [];
  for (const spec of chosen) {
    log(`${spec.group}/${spec.id}`);
    const outcome = await runCase(spec, [canary]);
    results.push({ id: spec.id, group: spec.group, description: spec.description, built: made[spec.id], results: outcome });
    for (const result of outcome.filter((entry) => !entry.ok)) log(`  FINDING ${result.op}: ${result.findings.join('; ')}`);
  }

  // What happened to the files around the root.
  const outside = host.run('sudo', ['-n', 'find', host.STATE, '/srv/vsift', '-xdev', '-newer', `${host.STATE}/queue/p14-stamp`, '!', '-path', host.STATE, '!', '-path', '/srv/vsift', '!', '-path', `${host.STATE}/ws-hostile*`, '!', '-path', `${host.STATE}/ws-small*`, '!', '-path', `${host.STATE}/home*`, '!', '-path', `${host.STATE}/queue*`, '!', '-path', `${host.STATE}/results*`]).stdout.split('\n').filter(Boolean);
  const canaryNow = host.run('sudo', ['-n', 'sha256sum', cases.CANARY_PATH]).stdout.split(' ')[0];
  const leaked = host.run('sudo', ['-n', 'grep', '-rl', '--binary-files=text', canary, WORKSPACE, WORKER_WORKSPACE, SMALL_WORKSPACE, host.BUNDLES, `${host.STATE}/home`]).stdout.split('\n').filter(Boolean);
  const pwned = host.run('sudo', ['-n', 'find', '/var/lib/vsift', '/srv/vsift', '/tmp', '-name', 'pwned', '-not', '-path', `${HOSTILE}/*`]).stdout.split('\n').filter(Boolean);
  const containment = [
    { name: 'no file was created or changed outside the root, the home and the queue', ok: outside.length === 0, detail: outside.length ? outside.slice(0, 5).join(', ') : 'nothing newer than the start of the run outside them' },
    { name: 'the canary outside the root is unchanged', ok: canaryNow === canaryDigest, detail: canaryNow === canaryDigest ? 'same SHA-256' : `now ${canaryNow}` },
    { name: 'the canary is in no session, bundle or configuration file', ok: leaked.length === 0, detail: leaked.length ? leaked.slice(0, 5).join(', ') : 'not found' },
    { name: 'no injected command ran (no file named pwned anywhere)', ok: pwned.length === 0, detail: pwned.length ? pwned.join(', ') : 'none found' },
  ];

  const operations = results.reduce((sum, entry) => sum + entry.results.length, 0);
  const findingsList = results.flatMap((entry) => entry.results.filter((result) => !result.ok).map((result) => ({ id: entry.id, op: result.op, findings: result.findings })));
  const all = results.flatMap((entry) => entry.results);
  const passingIds = results.filter((entry) => entry.results.every((result) => result.ok)).map((entry) => entry.id);
  const split = judge.splitKnown(findingsList, TRACKED, passingIds);
  const report = {
    ok: findingsList.length === 0 && containment.every((check) => check.ok),
    known: split.known,
    fresh: split.fresh,
    fixed: split.fixed,
    containmentOk: containment.every((check) => check.ok),
    cases: results.length,
    operations,
    findings: findingsList.length + containment.filter((check) => !check.ok).length,
    slowestSeconds: Math.max(0, ...all.map((result) => result.seconds)),
    peakMiB: Math.max(0, ...all.map((result) => result.memoryPeakMiB || 0)),
    results,
    findingsList,
    containment,
    version: JSON.parse(fs.readFileSync(path.join(options.out, 'host.json'), 'utf8')).versionLine,
    baseBytes: base.length,
  };
  fs.writeFileSync(path.join(options.out, 'hostile-result.json'), `${JSON.stringify(report, null, 2)}\n`);
  const text = markdown(report);
  fs.writeFileSync(path.join(options.out, 'hostile-summary.md'), text);
  process.stdout.write(`\n${text}\n`);
  // A new finding, or a broken containment check, fails the run; findings already filed (TRACKED) do not.
  process.exitCode = report.fresh.length === 0 && report.containmentOk ? 0 : 1;
}

main().catch((error) => {
  process.stderr.write(`${error.stack || error.message}\n`);
  process.exitCode = 2;
});
