// Reads `vsift --help` and the help of every command into a tree, and renders the
// command reference page from it (P14 PR 9b, docs/planning/user-guide-spec.md).
//
// The page is generated, never written by hand: the CLI's own help text is the
// only source, so the reference cannot drift from the code. A CI check
// (tools/guide/generate-reference.cjs --check) fails when the committed page is
// not what this module renders from the binary under test.

'use strict';

const childProcess = require('node:child_process');

/** What a help text looks like once the parts that depend on the machine are gone. */
function normaliseHelp(text) {
  return text
    .replace(/\r\n/g, '\n')
    // The executable's own name: `vsift.exe` on Windows, `vsift` elsewhere.
    .replace(/^Usage: vsift(?:\.exe)?(?= |$)/gm, 'Usage: vsift')
    .replace(/[ \t]+$/gm, '')
    .replace(/\n{3,}/g, '\n\n')
    .trimEnd();
}

/** The commands a help text lists under `Commands:`, as `{ name, summary }`. */
function listedCommands(help) {
  const lines = help.split('\n');
  const start = lines.indexOf('Commands:');
  if (start < 0) return [];
  const commands = [];
  for (const line of lines.slice(start + 1)) {
    if (line.trim() === '') break;
    const match = /^ {2}(\S+)\s{2,}(.*)$/.exec(line);
    if (!match) break;
    // The implicit `help` pseudo-command repeats what `--help` shows.
    if (match[1] !== 'help') commands.push({ name: match[1], summary: match[2].trim() });
  }
  return commands;
}

/** Runs the binary with `args`; a help text must come with exit status 0. */
function run(binary, args, env) {
  const result = childProcess.spawnSync(binary, args, { encoding: 'utf8', env, windowsHide: true, timeout: 60_000 });
  if (result.error) throw new Error(`could not run ${binary} ${args.join(' ')}: ${result.error.message}`);
  if (result.status !== 0) {
    throw new Error(`${binary} ${args.join(' ')} exited ${result.status}: ${result.stderr || result.stdout}`);
  }
  return result.stdout;
}

/** The version the binary reports (`vsift 0.2.0-rc.1 (abcdef012345)` gives `0.2.0-rc.1`). */
function readVersion(binary, env) {
  const line = run(binary, ['--version'], env).trim();
  const match = /^vsift (\S+)/.exec(line);
  if (!match) throw new Error(`unexpected --version line: ${line}`);
  return match[1];
}

/**
 * The release a version belongs to: `0.2.0-rc.1` and `0.2.0` are both `0.2.0`. The guide is
 * checked against and says the release, not the candidate, because the stable commit may differ
 * from its accepted candidate only in version-string files, shipped documents and the work record
 * (the release process, section 6.8), and the generated reference pages, which name the release,
 * are in none of them: a guide that named `0.2.0-rc.1` could not become `0.2.0` without a change
 * the stable cut refuses.
 */
function releaseOf(version) {
  const match = /^(\d+\.\d+\.\d+)(?:[-+].*)?$/.exec(version);
  if (!match) throw new Error(`not a version: ${version}`);
  return match[1];
}

/**
 * The whole command tree: `{ path, summary, help, children }`, the root first.
 * `path` is the words after `vsift`. `helpOf(args)` returns the help text for
 * `vsift <args>`; tests give it a table instead of a program.
 */
function readCommandTreeWith(helpOf) {
  const visit = (path, summary) => {
    const help = normaliseHelp(helpOf([...path, '--help']));
    const children = listedCommands(help).map((child) => visit([...path, child.name], child.summary));
    return { path, summary, help, children };
  };
  return visit([], 'The root command, with the options every command takes');
}

/** The command tree of a built binary. */
function readCommandTree(binary, env) {
  return readCommandTreeWith((args) => run(binary, args, env));
}

/** The tree flattened, depth first, in the order the help lists the commands. */
function flatten(node) {
  return [node, ...node.children.flatMap(flatten)];
}

/** The heading a command gets, which is also what the contents list links to. */
function headingOf(node) {
  return ['vsift', ...node.path].join(' ');
}

/** GitHub's and most static-site tools' anchor for a heading made of words and code marks. */
function anchorOf(heading) {
  return heading
    .toLowerCase()
    .replace(/[^a-z0-9 -]/g, '')
    .replace(/ /g, '-');
}

/** The Markdown of the command reference page. */
function renderCommands(tree, version) {
  const nodes = flatten(tree);
  const lines = [
    '# Command reference',
    '',
    '<!-- Generated by tools/guide/generate-reference.cjs from `vsift --help`. Do not edit by hand: a CI check fails when this page is out of date. -->',
    '',
    `> **Generated page.** What follows is the output of \`vsift --help\` and of \`--help\` on every command, from vsift ${version}, the version this guide was checked against. Do not edit it: change the help text in the CLI and run \`node tools/guide/generate-reference.cjs --write\`. For what the commands promise (exit statuses, JSON, failure codes) read [the CLI contract](../../contracts/cli-v1.md) and the generated [JSON reference](json.md); for how to use them, start with [the guide](../index.md).`,
    '',
    '## Contents',
    '',
    ...nodes.map((node) => `- [${headingOf(node)}](#${anchorOf(headingOf(node))}): ${node.summary}`),
    '',
  ];
  for (const node of nodes) {
    lines.push(`## ${headingOf(node)}`, '', node.summary + '.', '', '```text', node.help, '```', '');
  }
  return lines.join('\n');
}

module.exports = {
  anchorOf,
  flatten,
  headingOf,
  listedCommands,
  normaliseHelp,
  readCommandTree,
  readCommandTreeWith,
  readVersion,
  releaseOf,
  renderCommands,
  run,
};
